language: julia

os:
  - windows

julia:
  - 1.2

notifications:
  email:
    recipients: varga.andreas@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master


after_success:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Documenter", version="0.23"))' && julia docs/make.jl
  - julia -e 'using Pkg; cd(Pkg.dir("MatrixEquations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
 