language: julia

os:
  - windows

julia:
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: 1.3
    - julia: nightly


notifications:
  email:
    recipients: varga.andreas@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master


after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MatrixEquations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: windows
      script:
        - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Documenter"))' && julia docs/make.jl
      after_success: skip